{{ range $cluster := $.Values.clusters }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pathfinder-reference-api-{{ $cluster }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pathfinder
    server: {{ $.Values.spec.destination.server }}
  project: pathfinder
  source:
    path: ./chart
    repoURL: https://github.com/silvester-io-pathfinder/pathfinder-reference-api-gitops.git
    targetRevision: {{ $cluster }}
    helm:
      valueFiles:
        - values/common.yaml
        - values/{{$cluster}}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
---
{{ end }}