apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-credentials
  namespace: pathfinder
spec:
  encryptedData:
    .dockerconfigjson: AgAnyTzniSdOnwYd5TFKz44NOyeNerXXVljTbpGqC28h9f2Q5+4rNvpIlwQqTmWrDw+3aLc3pN/Q2U3ZdoAN1D5YgkkZVk9mzZnGsc3lHiAC4yKxHmC35p+e8PZoVEsXzZbGRbnULJtwL3FFM3HO8bWl1hNM++IY9VKCmHhkRmS4GZ9Il8Bxz/uUcgYV/eqOS3V228upRmqQ2+oslwL+NcrE0rKrAc5vmkFjetQo66rHVnl7NwdWZY3IN15Bx5jKa6zehYO8ZgVtBlNFuBr78vvC7dckW+0jLjhMf/jwYyoDAE4HIF3JTcdrpSwj0HRpSlDnrTMZaSzO38goILyGIDfqsYo4YqVpL+qGSt6OixV1zc53XNZALogyFYHmclO1qZokD/Ez+XmZKUhyF5G+x5MW57/+EP9pCk4/7Wo15XOqirEYeLTcXwtJrImupWdUdRXWWzbzddLlILtACdolxvl3A7fcuFNxqCnTGm85is9q340OlhM8NbI/mn94vmepCxPBQyBYCXzLA2oFQpCc8A4KWv35UZ817wRFrjmT4hmFG4KfmfiKvOPUw7fKAvlvqFgoGRxJs+RGh61wgnjBMRkvi9ESiJBSNOnCQCx3RB9w19izxkOF2fVe3w0dIT0R1ewDsQHt+RhqHDe48kf9/kwpuQfj6GtIQeA+LNvT5WOkbrlykIP69dEyK3tgEM9QW5PQgHnF800Y+SWIfmW7uNTRado3X+fjkfcebxIpXkxkqHGb8uyDg9uwLmaxKEl4SRCWUr2Ukp7VFFPALsfSL60J5qQRC4gM5cNGw1IYukUdIhkVs1djWehal/GSI7vcdIhBmjTIn/jOJvZ0h7sNgsMVBO3TLdBs8/MBUu5rnNpWRz5nO1CP2NIYGnpi06HfguYfv1HjnF2xbhz1f2IW7tJOQB1GDZXDehL1WVE4SQ4F0vAL6SF0lUvU7YEu/lIfSawrpWelf3TxqSW/AwF/88xQ
  template:
    metadata:
      creationTimestamp: null
      name: artifactory-credentials
      namespace: pathfinder
    type: kubernetes.io/dockerconfigjson

